"""baseline schema

Revision ID: 063c3fe2d739
Revises: e89c59c2a0a4
Create Date: 2026-09-21 12:00:06.803106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '063c3fe2d739'
down_revision: Union[str, Sequence[str], None] = 'e89c59c2a0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bookings_customer'), table_name='bookings')
    op.drop_index(op.f('idx_bookings_vehicle_dates'), table_name='bookings')
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_vehicle_id'), 'bookings', ['vehicle_id'], unique=False)
    op.drop_index(op.f('email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_categories_id'), 'vehicle_categories', ['id'], unique=False)
    op.alter_column('vehicles', 'manufacturing_year',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_vehicles_availability'), table_name='vehicles')
    op.drop_index(op.f('idx_vehicles_brand'), table_name='vehicles')
    op.drop_index(op.f('idx_vehicles_category'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_availability_status'), 'vehicles', ['availability_status'], unique=False)
    op.create_index(op.f('ix_vehicles_brand'), 'vehicles', ['brand'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_brand'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_availability_status'), table_name='vehicles')
    op.create_index(op.f('idx_vehicles_category'), 'vehicles', ['category_id'], unique=False)
    op.create_index(op.f('idx_vehicles_brand'), 'vehicles', ['brand'], unique=False)
    op.create_index(op.f('idx_vehicles_availability'), 'vehicles', ['availability_status'], unique=False)
    op.alter_column('vehicles', 'manufacturing_year',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_vehicle_categories_id'), table_name='vehicle_categories')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_bookings_vehicle_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.create_index(op.f('idx_bookings_vehicle_dates'), 'bookings', ['vehicle_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('idx_bookings_customer'), 'bookings', ['customer_id'], unique=False)
    # ### end Alembic commands ###
